# Generated by Django 4.2.7 on 2023-12-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Title',
            new_name='title',
        ),
    ]
