# Generated by Django 4.2.7 on 2023-12-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_title_job_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Industry',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='Industry',
        ),
    ]
