# Generated by Django 4.2.7 on 2023-12-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_company_industry_rename_company_job_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Industry',
            new_name='industry',
        ),
    ]
